const guidesChampData = [
  {
    title: 'Champion Guide: Aatrox',
    category: 'Champion guides',
    role: 'Top',
    difficulty: 'Intermediate',
    content: 'How to play Aatrox and item builds...',
    video: 'https://www.youtube.com/embed/GCIlwmhq4vk', 
  },
  {
    title: 'Champion Guide: Ahri',
    category: 'Champion guides',
    role: 'Mid',
    difficulty: 'Intermediate',
    content: 'Master the art of playing Ahri with these tips...',
    video: 'https://www.youtube.com/embed/RD9RzAaQF3Y',
  },
  {
    title: 'Champion Guide: Akali',
    category: 'Champion guides',
    role: 'Mid',
    difficulty: 'Advanced',
    content: 'Akali gameplay strategies and itemization...',
    video: 'https://www.youtube.com/embed/k4bLNNuaDgw',
  },
  {
    title: 'Champion Guide: Alistar',
    category: 'Champion guides',
    role: 'Support',
    difficulty: 'Beginner',
    content: 'Best ways to play Alistar as support...',
    video: 'https://www.youtube.com/embed/4ifouqudw_s',
  },
  {
    title: 'Champion Guide: Amumu',
    category: 'Champion guides',
    role: 'Jungle',
    difficulty: 'Beginner',
    content: 'How to effectively jungle with Amumu...',
    video: 'https://www.youtube.com/embed/x4uC-tp9MtE',
  },
  {
    title: 'Champion Guide: Annie',
    category: 'Champion guides',
    role: 'Mid',
    difficulty: 'Beginner',
    content: 'Tips for dominating mid lane with Annie...',
    video: 'https://www.youtube.com/embed/Ripn3K9kfeU',
  },
  {
    title: 'Champion Guide: Ashe',
    category: 'Champion guides',
    role: 'ADC',
    difficulty: 'Beginner',
    content: 'Ashe ADC guide: Laning phase and team fights...',
    video: 'https://www.youtube.com/embed/pUyy9Q7u3zU',
  },
  {
    title: 'Champion Guide: Azir',
    category: 'Champion guides',
    role: 'Mid',
    difficulty: 'Advanced',
    content: 'Maximize Azir\'s potential with these strategies...',
    video: 'https://www.youtube.com/embed/KdZ6H9O5bQ4',
  },
  {
    title: 'Champion Guide: Blitzcrank',
    category: 'Champion guides',
    role: 'Support',
    difficulty: 'Intermediate',
    content: 'Land every hook with this Blitzcrank guide...',
    video: 'https://www.youtube.com/embed/7jBP91e-xjo',
  },
  {
    title: 'Champion Guide: Caitlyn',
    category: 'Champion guides',
    role: 'ADC',
    difficulty: 'Intermediate',
    content: 'Control the bot lane with Caitlyn...',
    video: 'https://www.youtube.com/embed/FAYoheS4VUY',
  },
  {
    title: 'Champion Guide: Darius',
    category: 'Champion guides',
    role: 'Top',
    difficulty: 'Intermediate',
    content: 'Dominate the top lane with Darius...',
    video: 'https://www.youtube.com/embed/W0yxEk2bDHQ',
  },
  {
    title: 'Champion Guide: Draven',
    category: 'Champion guides',
    role: 'ADC',
    difficulty: 'Advanced',
    content: 'Carry your team as Draven ADC...',
    video: 'https://www.youtube.com/embed/3H36VhTIhSw',
  },
  {
    title: 'Champion Guide: Ekko',
    category: 'Champion guides',
    role: 'Mid',
    difficulty: 'Intermediate',
    content: 'Ekko mid lane guide: Combo and positioning...',
    video: 'https://www.youtube.com/embed/yRM4b6Y8PgY',
  },
  {
    title: 'Champion Guide: Elise',
    category: 'Champion guides',
    role: 'Jungle',
    difficulty: 'Advanced',
    content: 'Jungle pathing and ganking with Elise...',
    video: 'https://www.youtube.com/embed/BIMGAXXTpTk',
  },
  {
    title: 'Champion Guide: Evelynn',
    category: 'Champion guides',
    role: 'Jungle',
    difficulty: 'Advanced',
    content: 'Stealth and burst tactics with Evelynn...',
    video: 'https://www.youtube.com/embed/kMvedaiWrLI',
  },
  {
    title: 'Champion Guide: Fiora',
    category: 'Champion guides',
    role: 'Top',
    difficulty: 'Advanced',
    content: 'Fiora top lane guide: Duels and split pushing...',
    video: 'https://www.youtube.com/embed/jhak6HMxRUU',
  },
  {
    title: 'Champion Guide: Fizz',
    category: 'Champion guides',
    role: 'Mid',
    difficulty: 'Advanced',
    content: 'Assassinate your enemies with Fizz...',
    video: 'https://www.youtube.com/embed/dwXorhwb2Jo',
  },
  {
    title: 'Champion Guide: Garen',
    category: 'Champion guides',
    role: 'Top',
    difficulty: 'Beginner',
    content: 'Garen top lane guide: Sustain and damage...',
    video: 'https://www.youtube.com/embed/W5UvZMBZKM0',
  },
  {
    title: 'Champion Guide: Gragas',
    category: 'Champion guides',
    role: 'Jungle',
    difficulty: 'Intermediate',
    content: 'Flex your Gragas skills in jungle and top lane...',
    video: 'https://www.youtube.com/embed/lD8_ne9pD40',
  },
  {
    title: 'Champion Guide: Hecarim',
    category: 'Champion guides',
    role: 'Jungle',
    difficulty: 'Intermediate',
    content: 'Charge through your enemies with Hecarim...',
    video: 'https://www.youtube.com/embed/nMYYSndQoqQ',
  },
  {
    title: 'Champion Guide: Janna',
    category: 'Champion guides',
    role: 'Support',
    difficulty: 'Beginner',
    content: 'Shield and support your team with Janna...',
    video: 'https://www.youtube.com/embed/UQFobYXalYY',
  },
  {
    title: 'Champion Guide: Jax',
    category: 'Champion guides',
    role: 'Top',
    difficulty: 'Intermediate',
    content: 'Master Jax in the top lane with these tips...',
    video: 'https://www.youtube.com/embed/vjWSf17IAlY',
  },
  {
    title: 'Champion Guide: Jhin',
    category: 'Champion guides',
    role: 'ADC',
    difficulty: 'Advanced',
    content: 'Precise shots and positioning with Jhin...',
    video: 'https://www.youtube.com/embed/OqR9SdL6ESM',
  },
  {
    title: 'Champion Guide: Jinx',
    category: 'Champion guides',
    role: 'ADC',
    difficulty: 'Intermediate',
    content: 'Blow up your enemies with Jinx ADC...',
    video: 'https://www.youtube.com/embed/ZSXYUpjN7yE',
  },
  {
    title: 'Champion Guide: Kai\'Sa',
    category: 'Champion guides',
    role: 'ADC',
    difficulty: 'Intermediate',
    content: 'Adapt and overcome with Kai\'Sa ADC...',
    video: 'https://www.youtube.com/embed/MtQWCFwbE5k',
  },
  {
    title: 'Champion Guide: Katarina',
    category: 'Champion guides',
    role: 'Mid',
    difficulty: 'Advanced',
    content: 'Unleash your full combo with Katarina...',
    video: 'https://www.youtube.com/embed/QBJcaEw9HFI',
  },
  {
    title: 'Champion Guide: Kha\'Zix',
    category: 'Champion guides',
    role: 'Jungle',
    difficulty: 'Intermediate',
    content: 'Evolve and dominate with Kha\'Zix...',
    video: 'https://www.youtube.com/embed/FUmCYDSGVic',
  },
  {
    title: 'Champion Guide: Lee Sin',
    category: 'Champion guides',
    role: 'Jungle',
    difficulty: 'Advanced',
    content: 'Kick your way to victory with Lee Sin...',
    video: 'https://www.youtube.com/embed/Gs0qc7nek9w',
  },
  {
    title: 'Champion Guide: LeBlanc',
    category: 'Champion guides',
    role: 'Mid',
    difficulty: 'Advanced',
    content: 'Deceive and burst with LeBlanc...',
    video: 'https://www.youtube.com/embed/K5xzEoMGBjg',
  },
  {
    title: 'Champion Guide: Leona',
    category: 'Champion guides',
    role: 'Support',
    difficulty: 'Intermediate',
    content: 'Tank and engage with Leona support...',
    video: 'https://www.youtube.com/embed/2AVpDep3nM8',
  },
  {
    title: 'Champion Guide: Lux',
    category: 'Champion guides',
    role: 'Mid',
    difficulty: 'Beginner',
    content: 'Illuminate your path to victory with Lux...',
    video: 'https://www.youtube.com/embed/xnagExyowDg',
  },
  {
    title: 'Champion Guide: Malphite',
    category: 'Champion guides',
    role: 'Top',
    difficulty: 'Beginner',
    content: 'Rock solid strategies for Malphite top...',
    video: 'https://www.youtube.com/embed/gULIW2qjox0',
  },
  {
    title: 'Champion Guide: Master Yi',
    category: 'Champion guides',
    role: 'Jungle',
    difficulty: 'Beginner',
    content: 'Carry games with Master Yi jungle...',
    video: 'https://www.youtube.com/embed/QLsAYapLmko',
  },
  {
    title: 'Champion Guide: Miss Fortune',
    category: 'Champion guides',
    role: 'ADC',
    difficulty: 'Intermediate',
    content: 'Rain bullets with Miss Fortune ADC...',
    video: 'https://www.youtube.com/embed/GC3vyX3sTZg',
  },
  {
    title: 'Champion Guide: Nami',
    category: 'Champion guides',
    role: 'Support',
    difficulty: 'Intermediate',
    content: 'Wave your way to victory with Nami...',
    video: 'https://www.youtube.com/embed/R1uZbk4IMoU',
  },
  {
    title: 'Champion Guide: Nautilus',
    category: 'Champion guides',
    role: 'Support',
    difficulty: 'Intermediate',
    content: 'Anchor down and engage with Nautilus...',
    video: 'https://www.youtube.com/embed/0nIR5FGHIs0',
  },
  {
    title: 'Champion Guide: Nidalee',
    category: 'Champion guides',
    role: 'Jungle',
    difficulty: 'Advanced',
    content: 'Pounce on your foes with Nidalee...',
    video: 'https://www.youtube.com/embed/MgYmqDthBkI',
  },
  {
    title: 'Champion Guide: Renekton',
    category: 'Champion guides',
    role: 'Top',
    difficulty: 'Intermediate',
    content: 'Slice and dice with Renekton top...',
    video: 'https://www.youtube.com/embed/UmXiuRZMB_Y',
  },
  {
    title: 'Champion Guide: Riven',
    category: 'Champion guides',
    role: 'Top',
    difficulty: 'Advanced',
    content: 'Master combos and mobility with Riven...',
    video: 'https://www.youtube.com/embed/z2ExpUD6mHk',
  },
  {
    title: 'Champion Guide: Sivir',
    category: 'Champion guides',
    role: 'ADC',
    difficulty: 'Intermediate',
    content: 'Boomerang your way to victory with Sivir...',
    video: 'https://www.youtube.com/embed/pA9r5hVKovs',
  },
  {
    title: 'Champion Guide: Sona',
    category: 'Champion guides',
    role: 'Support',
    difficulty: 'Beginner',
    content: 'Harmonize your gameplay with Sona...',
    video: 'https://www.youtube.com/embed/6WBccgKfp2Q',
  },
  {
    title: 'Champion Guide: Soraka',
    category: 'Champion guides',
    role: 'Support',
    difficulty: 'Beginner',
    content: 'Heal and sustain with Soraka support...',
    video: 'https://www.youtube.com/embed/doOTzKmlTsY',
  },
  {
    title: 'Champion Guide: Teemo',
    category: 'Champion guides',
    role: 'Top',
    difficulty: 'Intermediate',
    content: 'Annoy and dominate with Teemo...',
    video: 'https://www.youtube.com/embed/gvRmJsxoAio',
  },
  {
    title: 'Champion Guide: Thresh',
    category: 'Champion guides',
    role: 'Support',
    difficulty: 'Intermediate',
    content: 'Hook and flay with Thresh support...',
    video: 'https://www.youtube.com/embed/orRMuMoL0Fc',
  },
  {
    title: 'Champion Guide: Tristana',
    category: 'Champion guides',
    role: 'ADC',
    difficulty: 'Beginner',
    content: 'Explosive gameplay with Tristana ADC...',
    video: 'https://www.youtube.com/embed/Mv0Pz9QP6iU',
  },
  {
    title: 'Champion Guide: Vayne',
    category: 'Champion guides',
    role: 'ADC',
    difficulty: 'Intermediate',
    content: 'Tumble your way to victory with Vayne...',
    video: 'https://www.youtube.com/embed/nt8S3EEl68M',
  },
  {
    title: 'Champion Guide: Warwick',
    category: 'Champion guides',
    role: 'Jungle',
    difficulty: 'Beginner',
    content: 'Hunt and heal with Warwick jungle...',
    video: 'https://www.youtube.com/embed/1k3-dqQswq4',
  },
  {
    title: 'Champion Guide: Yasuo',
    category: 'Champion guides',
    role: 'Mid',
    difficulty: 'Advanced',
    content: 'Wind your way to victory with Yasuo...',
    video: 'https://www.youtube.com/embed/6gn9l3yn6d8',
  },
  {
    title: 'Champion Guide: Zed',
    category: 'Champion guides',
    role: 'Mid',
    difficulty: 'Advanced',
    content: 'Shadow and assassinate with Zed...',
    video: 'https://www.youtube.com/embed/5B-v2iW06AM',
  },
  {
    title: 'Inventory Guide: Best Items',
    category: 'Inventory guides',
    role: '',
    difficulty: 'Beginner',
    content: 'A comprehensive guide to the best items...',
    video: 'https://www.youtube.com/embed/9Y5m9euBkHU',
  },
  {
    title: 'Beginner Tips: Getting Started',
    category: 'Beginner\'s tips',
    role: '',
    difficulty: 'Beginner',
    content: 'Tips and tricks for new players...',
    video: 'https://www.youtube.com/embed/tQbo2X2Qysc',
  },
];

export default guidesChampData;
