const translations = {
    en: {
      home: 'Home',
      champions: 'Champions',
      guides: 'Guides',
      community: 'Community Page',
      joinUs: 'Join Us',
      'home.welcome': 'Welcome to LoLProClub',
      'home.description': 'We are the ultimate resource for League of Legends players. Our community offers comprehensive guides, real-time match analysis, and a platform to connect with other fans. Whether you\'re a newbie or a seasoned pro, LoLProClub has something for everyone. Join us and take your gameplay to the next level.',
      'home.joinUsButton': 'Join Us',
      'home.featuredNews': 'Featured News',
      'home.lastMonth': 'Last Month',
      'home.fakerDoc': 'Hall of Legends: Faker',
      'home.fakerDocDesc': 'Watch the full documentary on Faker, celebrating his unbelievable and unfinished career.',
      'home.devUpdate': 'Dev Update: Gameplay, Esports & Arcane',
      'home.devUpdateDesc': 'Updates on champions, mastery, Vanguard, esports, Arcane, and a teaser for season two.',
      'home.gameUpdates': 'Game Updates | 3 Weeks Ago',
      'home.patchNotes': 'LoL Patch 14.14 Notes',
      'home.patchNotesDesc': 'Patch 14.14 is making a splash.',
      'home.communityHighlights': 'Community Highlights',
      'home.highlightVideo': 'Highlight Video',
      'home.highlightVideoP1': 'Highlight Video 1',
      'home.highlightVideoP2': 'Highlight Video 2',
      'home.highlightVideoP3': 'Highlight Video 3',
      'champions.pageTitle': 'Champions Page',
      'champions.searchPlaceholder': 'Search champions...',
      'champions.allRoles': 'All Roles',
      'champions.top': 'Top',
      'champions.mid': 'Mid',
      'champions.jungle': 'Jungle',
      'champions.adc': 'ADC',
      'champions.support': 'Support',
      'guides.pageTitle': 'Guides Page',
      'guides.searchPlaceholder': 'Search guides...',
      'guides.allCategories': 'All Categories',
      'guides.championGuides': 'Champion guides',
      'guides.inventoryGuides': 'Inventory guides',
      'guides.beginnerTips': 'Beginner\'s tips',
      'guides.allRoles': 'All Roles',
      'guides.allDifficultyLevels': 'All Difficulty Levels',
      'guides.beginner': 'Beginner',
      'guides.intermediate': 'Intermediate',
      'guides.advanced': 'Advanced',
      'community.pageTitle': 'Community Page',
      'community.championSpotlight': 'Champion Spotlight',
      'community.thisWeekAhri': 'This week: Ahri - The Nine-Tailed Fox',
      'community.ahriGuide': 'Ahri Guide',
      'community.communityTournaments': 'Community Tournaments',
      'community.joinTournaments': 'Join our upcoming tournaments and compete for glory!',
      'community.registerHere': 'Register Here',
      'community.playerOfTheMonth': 'Player of the Month',
      'community.congratsPlayer': 'Congratulations to [Player Name] for outstanding contributions!',
      'community.eventCalendar': 'Event Calendar',
      'community.leaderboard': 'Leaderboard',
      'community.topCommunity': 'See who’s on top of the community challenges.',
      'community.patchNotesHighlights': 'Patch Notes Highlights',
      'community.latestPatchUpdates': 'Catch up on the latest patch updates and community reactions.',
      'community.patchNotes': 'Patch Notes',
      'community.streamerSpotlight': 'Streamer Spotlight',
      'community.featuredStreamers': 'Check out this week\'s featured streamers.',
      'community.twitch': 'Twitch',
      'community.weeklyChallenges': 'Weekly Challenges',
      'community.completeChallenges': 'Complete weekly challenges and earn rewards.',
      'community.startQuiz': 'Start Quiz',
      'community.quizQuestion': 'Quiz Question',
      'community.yourResults': 'Your Results',
      'community.congratulations': 'Congratulations! Enter your email to receive a gift card:',
      'community.enterEmail': 'Enter your email',
      'community.submit': 'Submit',
      'community.goodLuckNextTime': 'Good luck next time!',
      'community.retakeQuiz': 'Retake Quiz',
      'joinUs.pageTitle': 'Join Us Page',
      'joinUs.joinInstructions': 'Information on how to join goes here...',
      'joinUs.name': 'Name:',
      'joinUs.email': 'Email:',
      'joinUs.rank': 'Current Rank:',
      'joinUs.selectRank': 'Select your rank',
      'joinUs.frequency': 'How often do you play LoL?',
      'joinUs.selectFrequency': 'Select frequency',
      'joinUs.reason': 'Why do you want to join us?',
      'joinUs.submit': 'Submit',
      'joinUs.confirmInfo': 'Confirm Your Information',
      'joinUs.nameLabel': 'Name:',
      'joinUs.emailLabel': 'Email:',
      'joinUs.rankLabel': 'Current Rank:',
      'joinUs.frequencyLabel': 'How often do you play LoL?',
      'joinUs.reasonLabel': 'Reason for joining:',
      'joinUs.edit': 'Edit',
      'joinUs.finalSubmit': 'Submit',
      'joinUs.createClub': 'Create Your Own Club',
      'joinUs.step': 'Step',
      'joinUs.clubName': 'Club Name:',
      'joinUs.rolesNeeded': 'Roles Needed:',
      'joinUs.frequencyOfPlay': 'Frequency of Play:',
      'joinUs.minRank': 'Minimum Rank:',
      'joinUs.maxRank': 'Maximum Rank:',
      'joinUs.additionalInfo': 'Additional Information:',
      'joinUs.back': 'Back',
      'joinUs.next': 'Next',
    'joinUs.createClubBtn': 'Create Club',
    'joinUs.availableClubs': 'Available Clubs',
      'joinUs.description': 'Description:',
      'joinUs.join': 'Join',
      'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'How can I join the club?',
    'faq.a1': 'To join the club, click on the Join Us link in the navigation bar and fill out the form.',
    'faq.q2': 'What events are available?',
    'faq.a2': 'Check out our event calendar on the Community Page for upcoming events.',
    'faq.q3': 'How can I participate in the weekly challenge?',
    'faq.a3': 'You can participate in the weekly challenge by visiting the Community Page and following the instructions.',
    'faq.askQuestion': 'Ask a Question',
    'faq.newQuestionPlaceholder': 'Enter your question...',
    'faq.submitQuestion': 'Submit',
    'faq.newAnswerPlaceholder': 'Thank you for your question! We will provide an answer soon.',
    },
    fr: {
      home: 'Accueil',
      champions: 'Champions',
      guides: 'Guides',
      community: 'Page Communautaire',
      joinUs: 'Rejoignez-nous',
      'home.welcome': 'Bienvenue à LoLProClub',
      'home.description': 'Nous sommes la ressource ultime pour les joueurs de League of Legends. Notre communauté offre des guides complets, une analyse en temps réel des matchs et une plateforme pour se connecter avec d\'autres fans. Que vous soyez un novice ou un pro chevronné, LoLProClub a quelque chose pour tout le monde. Rejoignez-nous et faites passer votre gameplay au niveau supérieur.',
      'home.joinUsButton': 'Rejoignez-nous',
      'home.featuredNews': 'Actualités à la une',
      'home.lastMonth': 'Le mois dernier',
      'home.fakerDoc': 'Hall of Legends: Faker',
      'home.fakerDocDesc': 'Regardez le documentaire complet sur Faker, célébrant sa carrière incroyable et inachevée.',
      'home.devUpdate': 'Mise à jour des développeurs: Gameplay, Esports & Arcane',
      'home.devUpdateDesc': 'Mises à jour sur les champions, la maîtrise, Vanguard, les sports électroniques, Arcane et un teaser pour la saison deux.',
      'home.gameUpdates': 'Mises à jour du jeu | Il y a 3 semaines',
      'home.patchNotes': 'Notes de mise à jour LoL 14.14',
      'home.patchNotesDesc': 'La mise à jour 14.14 fait sensation.',
      'home.communityHighlights': 'Moments forts de la communauté',
      'home.highlightVideo': 'Vidéo de point culminant',
      'home.highlightVideoP1': 'Vidéo en Vedette 1',
      'home.highlightVideoP2': 'Vidéo en Vedette 2',
      'home.highlightVideoP3': 'Vidéo en Vedette 3',
      'champions.pageTitle': 'Page des Champions',
      'champions.searchPlaceholder': 'Rechercher des champions...',
      'champions.allRoles': 'Tous les rôles',
      'champions.top': 'Haut',
      'champions.mid': 'Milieu',
      'champions.jungle': 'Jungle',
      'champions.adc': 'ADC',
      'champions.support': 'Soutien',
      'guides.pageTitle': 'Page des Guides',
      'guides.searchPlaceholder': 'Rechercher des guides...',
      'guides.allCategories': 'Toutes les catégories',
      'guides.championGuides': 'Guides des champions',
      'guides.inventoryGuides': 'Guides d\'inventaire',
      'guides.beginnerTips': 'Conseils pour débutants',
      'guides.allRoles': 'Tous les rôles',
      'guides.allDifficultyLevels': 'Tous les niveaux de difficulté',
      'guides.beginner': 'Débutant',
      'guides.intermediate': 'Intermédiaire',
      'guides.advanced': 'Avancé',
      'community.pageTitle': 'Page Communautaire',
      'community.championSpotlight': 'Projecteur sur le Champion',
      'community.thisWeekAhri': 'Cette semaine : Ahri - Le Renard à Neuf Queues',
      'community.ahriGuide': 'Guide d\'Ahri',
      'community.communityTournaments': 'Tournois Communautaires',
      'community.joinTournaments': 'Rejoignez nos prochains tournois et concourez pour la gloire !',
      'community.registerHere': 'Inscrivez-vous ici',
      'community.playerOfTheMonth': 'Joueur du Mois',
      'community.congratsPlayer': 'Félicitations à [Nom du Joueur] pour ses contributions exceptionnelles !',
      'community.eventCalendar': 'Calendrier des Événements',
      'community.leaderboard': 'Classement',
      'community.topCommunity': 'Voyez qui est en tête des défis communautaires.',
      'community.patchNotesHighlights': 'Points Forts des Notes de Patch',
      'community.latestPatchUpdates': 'Mettez-vous à jour sur les dernières notes de patch et réactions de la communauté.',
      'community.patchNotes': 'Notes de Patch',
      'community.streamerSpotlight': 'Projecteur sur les Streamers',
      'community.featuredStreamers': 'Découvrez les streamers vedettes de cette semaine.',
      'community.twitch': 'Twitch',
      'community.weeklyChallenges': 'Défis Hebdomadaires',
      'community.completeChallenges': 'Complétez des défis hebdomadaires et gagnez des récompenses.',
      'community.startQuiz': 'Commencer le Quiz',
      'community.quizQuestion': 'Question du Quiz',
      'community.yourResults': 'Vos Résultats',
      'community.congratulations': 'Félicitations ! Entrez votre email pour recevoir une carte cadeau :',
      'community.enterEmail': 'Entrez votre email',
      'community.submit': 'Soumettre',
      'community.goodLuckNextTime': 'Bonne chance pour la prochaine fois !',
      'community.retakeQuiz': 'Reprendre le Quiz',
      'joinUs.pageTitle': 'Page Rejoignez-nous',
      'joinUs.joinInstructions': 'Les informations sur la façon de rejoindre vont ici...',
      'joinUs.name': 'Nom :',
      'joinUs.email': 'Email :',
      'joinUs.rank': 'Rang Actuel :',
      'joinUs.selectRank': 'Sélectionnez votre rang',
      'joinUs.frequency': 'À quelle fréquence jouez-vous à LoL ?',
      'joinUs.selectFrequency': 'Sélectionnez la fréquence',
      'joinUs.reason': 'Pourquoi voulez-vous nous rejoindre ?',
      'joinUs.submit': 'Soumettre',
      'joinUs.confirmInfo': 'Confirmez vos informations',
      'joinUs.nameLabel': 'Nom :',
      'joinUs.emailLabel': 'Email :',
      'joinUs.rankLabel': 'Rang Actuel :',
      'joinUs.frequencyLabel': 'À quelle fréquence jouez-vous à LoL ?',
      'joinUs.reasonLabel': 'Raison de rejoindre :',
      'joinUs.edit': 'Modifier',
      'joinUs.finalSubmit': 'Soumettre',
      'joinUs.createClub': 'Créez votre propre club',
      'joinUs.step': 'Étape',
      'joinUs.clubName': 'Nom du Club :',
      'joinUs.rolesNeeded': 'Rôles nécessaires :',
      'joinUs.frequencyOfPlay': 'Fréquence de jeu :',
      'joinUs.minRank': 'Rang Minimum :',
      'joinUs.maxRank': 'Rang Maximum :',
      'joinUs.additionalInfo': 'Informations supplémentaires :',
      'joinUs.back': 'Retour',
      'joinUs.next': 'Suivant',
      'joinUs.createClubBtn': 'Créer un club',
      'joinUs.availableClubs': 'Clubs Disponibles',
      'joinUs.description': 'Description:',
      'joinUs.join': 'Rejoindre',
      'faq.title': 'Questions fréquemment posées',
    'faq.q1': 'Comment puis-je rejoindre le club ?',
    'faq.a1': 'Pour rejoindre le club, cliquez sur le lien Rejoignez-nous dans la barre de navigation et remplissez le formulaire.',
    'faq.q2': 'Quels événements sont disponibles ?',
    'faq.a2': 'Consultez notre calendrier des événements sur la Page Communautaire pour les événements à venir.',
    'faq.q3': 'Comment puis-je participer au défi hebdomadaire ?',
    'faq.a3': 'Vous pouvez participer au défi hebdomadaire en visitant la Page Communautaire et en suivant les instructions.',
    'faq.askQuestion': 'Posez une question',
    'faq.newQuestionPlaceholder': 'Entrez votre question...',
    'faq.submitQuestion': 'Soumettre',
    'faq.newAnswerPlaceholder': 'Merci pour votre question! Nous vous fournirons une réponse bientôt.',
    },
    default: 'en',
  };
  
  export default translations;
  